"""empty message

Revision ID: c5252bf27b11
Revises: 
Create Date: 2024-11-14 15:33:14.407407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5252bf27b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.DateTime(), server_default=sa.text('new()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nom'),
    sa.UniqueConstraint('prenom')
    )
    op.drop_table('mission')
    op.drop_table('personnel')
    op.drop_table('situation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situation',
    sa.Column('id_situation', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('statut_de_projet', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('financement', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_situation'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('personnel',
    sa.Column('id_personne', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('numero', mysql.INTEGER(display_width=20), autoincrement=False, nullable=False),
    sa.Column('statut', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_personne'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mission',
    sa.Column('id_mission', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tache_a_faire', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id_mission'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
